### ISSUE TITLE
License type change to MIT

### ISSUE THREAD

**Issue by sheldonhull** [dfinke/PowerShellHumanizer#12]
Would you be willing to change the license type to MIT? This is more permissible and easier to use in context of commercial environments. Some similar projects like dbatools and others have migrated over to this license to allow much more flexible usage.

Additionally, I'd like to add more functionality for formatting timespans, dates. Do you want some pull requests to collaborate or is this current repository not actively maintained? 

Thanks!

**Comment by cdhunt** [comment]
The only requirement of Apache 2 is you preserve copyright and license notices with the source. It supports commercial use. However, I'm fine with MIT if @dfinke is.

We're definitely open to PRs, but keep in mind most of the "logic" is in the upstream [Humanizer](https://github.com/MehdiK/Humanizer) project.

**Comment by dfinke** [comment]
@cdhunt already changed to MIT. @sheldonhull if you need the logic changed in the C# project, let me know, I worked with Oren, should be able to get PRs approved.

**Comment by sheldonhull** [comment]
@dfinke  you guys are awesome thanks for this. And yes, if it's possible to update the license in both this and the c# that would be awesome. Not a deal breaker, but I can tell you the MIT license type has been slightly more flexible in cases where I needed to reuse a specific function or component and not the entire whole. 

Either way, I appreciate the quick response, and hopefully can submit some PR's if I'm able to add some extensibility to this. 

A related question... is there anyway to get the module to autoload when using the extensions created? Without explicit import? For instance  .Humanize() fails if not imported already, so I'd like to figure a way to prevent that by autoloading if not loaded.

**Comment by dfinke** [comment]
Please post to the Humanizer the same request and reference this thread. Let's start there.

**Comment by onovotny** [comment]
Humanizer is already MIT:
