### ISSUE TITLE
Improve custom Type member scripts

### ISSUE THREAD

**Issue by cdhunt** [dfinke/PowerShellHumanizer#5]
- Formal Param with strict types
- Move to Type file
- Improve member naming to match Powershell conventions

**Comment by dfinke** [comment]
Cool, so you want to move the registering from the psm1 out to the ps1xml? Nice catch on the spelling ;-)

**Comment by cdhunt** [comment]
That seems like the correct place and breaking up the module makes it easier to collaborate on.

**Comment by dfinke** [comment]
Makes sense!

**Comment by cdhunt** [comment]
How should we handle custom properties that call parameter-less methods.

For example, should the implementation of `Dehumanize()` be a ScriptProperty named `Dehumanize` or `Dehumanized` or should it be a ScriptMethod to match the source and be `Dehumanize()`?

**Comment by cdhunt** [comment]
I've pushed up type files that cover the existing custom types to the branch Feature_TypeFiles. It broke one of the cmdlets.

**Comment by dfinke** [comment]
Thanks. I need to look at the PRs in my import excel this weekend. Which did it break? It'd be cool to merge this

**Comment by cdhunt** [comment]
It was `ConvertTo-HyphenatedString`. I just fixed that. Need to update the docs then it should be ready for merging.

**Comment by cdhunt** [comment]
ETS scripts have been moved to ps1xml files with some minor improvements.
