### ISSUE TITLE
Surface more options on casing

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellHumanizer#8]
"CanReturnTitleCase".Humanize(LetterCasing.Title) => "Can Return Title Case"

"Can_return_title_Case".Humanize(LetterCasing.Title) => "Can Return Title Case"

"CanReturnLowerCase".Humanize(LetterCasing.LowerCase) => "can return lower case"

"CanHumanizeIntoUpperCase".Humanize(LetterCasing.AllCaps) => "CAN HUMANIZE INTO UPPER CASE"

**Comment by dfinke** [comment]
@cdhunt 

Implemented the `LetterCasing.Title`. Wondering about the best way to extended `Get-Command` to include this?

![image](https://cloud.githubusercontent.com/assets/67258/14693356/112570f2-072c-11e6-8c88-f1087760a577.png)

**Comment by cdhunt** [comment]
Add a script property to System.Management.Automation.CmdletInfo. I'm not sure if there's much value in humanizing aliases. Most are just acronyms.

**Comment by dfinke** [comment]
Cool, good point. Add the property in the ps1xml?

**Comment by cdhunt** [comment]
I think to do it property, we'd create a new custom property, either through Update-Type or a Type XML file, and then create a Format XML to display the new property. This goes back to #5 and refactoring how the custom types are managed.

**Comment by cdhunt** [comment]
Now supports all of the casing options for Humanize as well as the Transform. Added a `Humanized` parameter to `CmdletInfo` and `FunctionInfo` types.
